### ISSUE TITLE
Redirect URI

### ISSUE THREAD

**Issue by hons82** [anthonychwong/auth0-flutter-web#10]
Hi, 
I think I have it almost right, but I can't figure out the correct callback-url. 
I've set the redirect_uri to a callback url in the list, but I still get, that it is not allowed. 
Do you have some hint for me?

**Comment by anthonychwong** [comment]
Hi,

Could you provide some code to reproducing your problem, and some screenshot of it?

**Comment by anthonychwong** [comment]
I'm closing this issue because it has been inactive.
