### ISSUE TITLE
Help : Flutter auth0 Web with Discord oauth2

### ISSUE THREAD

**Issue by mohamis** [anthonychwong/auth0-flutter-web#2]
Hello ! :)

Thanks for your package it’s helpful ! 
I have a problem I am using Discord oauth2 and with Auth0 it’s making an error as Auth0 is using a scope that is not supported by Discord (openid) :\
So I have a question about how to customize the scopes for the request, I’ve seen that Auth0 take as option scopes parameters when you create the auth0 client but could you add on this package as well the option to use a different redirect page ?
If you can it could be very helpful :)

thanks in advance !! 🙌

**Comment by anthonychwong** [comment]
Hi there, the code with these options is in #3 , but I am struggling on serving the webapp on `https` and hence cannot trigger discord for testing yet. Could you help on this?

_UPDATE_: The redirect URL for discord should be from Auth0, so the flutter web app don't necessarily be served by https.

**Comment by anthonychwong** [comment]
I've tested and just published [`alpha-3`](https://pub.dev/packages/auth0_flutter_web/versions/0.0.1-alpha.3) that supports this option. Let me know if this version have other issues as well.

For some reason, `pub.dev` don't serve this version by default, you'll need to specify the version in dependencies.

**Comment by anthonychwong** [comment]
I'm closing this issue because it has been inactive.

**Comment by vanlooverenkoen** [comment]
We are having the same issue with Strava. `activity:write,read` is the scope we need. But openId, Email & profile are added. Which are not all supported resulting in an invalid scope. How can we fix this?

**Comment by anthonychwong** [comment]
Hi, could you provide sample project for me to check? Also, does this works with plain Auth0 plain SPA SDK?
