### ISSUE TITLE
Returning short token - not JWT

### ISSUE THREAD

**Issue by tfnaylor** [anthonychwong/auth0-flutter-web#4]
I have found that the getTokenWithPopup() function returns a shortened token that is not a valid JWT. I found through another article that to get the JWT you need to specify the audience. Would it be possible to update this package to allow the user to specify the audience in the getTokenWithPopup() function (using options)? 

Here is the article where I learned that the audience value is required to get the full JWT:

https://stackoverflow.com/questions/62944179/auth0-returns-a-short-accesstoken-in-the-flutter-environment

**Comment by tfnaylor** [comment]
I was able to get a valid JWT by simply adding the 'audience' option to Auth0CreateOptions. Would you like a pull request or would you prefer to simply update the code yourself?

**Comment by anthonychwong** [comment]
Thanks for the findings. I will add other options to align these parameters with the official SPA SDK this weekend.

**Comment by tfnaylor** [comment]
Ok perfect. One of my employees that has a lot of experience with Auth0 in Angular web applications has forked this repo and is adding several other useful functions available in the SDK. Would you like us to create a pull request to incorporate these features once we have tested them?

**Comment by anthonychwong** [comment]
Sure, thanks for that

**Comment by anthonychwong** [comment]
[`0.0.1-alpha.4`](https://pub.dev/packages/auth0_flutter_web/versions/0.0.1-alpha.4) is released thus `audience` option is available for both `createAuth0Client` and `getTokenWithPopup` (which not served by default, again).

Let me know if any other problems with the new release.

**Comment by anthonychwong** [comment]
I'm closing this issue because it has been inactive.
